# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.19.3
#   kernelspec:
#     display_name: lulc-classification
#     language: python
#     name: lulc-classification
# ---

# %% [markdown]
# # Rasterio metadata
#
# This notebook exists because I forgot to add band names to the seasonal rasters and worldcover labels, so, instead of re-running AGAIN the entire pipeline, we will fix it here.

# %%
# %load_ext autoreload
# %autoreload 2

# %%
import os
import sys

sys.path.append(os.path.abspath(".."))

# %%
from pathlib import Path

import numpy as np
from src.io import SEASONAL_SCENES, GLOBAL_CONFIG, WORLDCOVER_LABELS
from src.config import load_config
from src.constants import  seasonal_band_names, SEASONS_ORDER
import rasterio
import rioxarray as rxr

# %%
cfg = load_config(GLOBAL_CONFIG)

# %% [markdown]
# ## Seasonal features

# %%
SEASONAL_SCENES

# %%
# !gdalinfo {SEASONAL_SCENES[0]}

# %% [markdown]
# We can see that `Band` does not have a field called `Description`.

# %%
cfg.msi.get_bands_list()

# %% [markdown]
# Since we would like in the future to support other data providers from the Sentinel-2 imagery, not only CDSE, we created a conversion layer on top of the names specified in the MSI config:

# %%
cfg.msi.band_names

# %% [markdown]
# Moreover, we don't have only reflectance bands, but also indices. So, the names we want to add to the raster are:

# %%
seasonal_band_names(cfg.msi)

# %% [markdown]
# Let's now add the information about the band names by opening the raster in read and write mode:

# %%
with rasterio.open(SEASONAL_SCENES[0], "r+") as src:
    src.descriptions = tuple(seasonal_band_names(cfg.msi))
    tags = src.tags()

# %% [markdown]
# Now we have the `Description` populated:

# %%
# !gdalinfo {SEASONAL_SCENES[0]} | grep "Description"

# %% [markdown]
# We could also add more metadata in the form of tags, like the seaon names:

# %%
tags

# %%
for scene, season in zip(SEASONAL_SCENES, SEASONS_ORDER):
    with rasterio.open(scene, "r+") as src:
        src.descriptions = tuple(seasonal_band_names(cfg.msi))
        src.update_tags(season=season)

# %%
# !gdalinfo {SEASONAL_SCENES[0]} | grep "season="

# %% [markdown]
# ## Labels
#
# For the creation of the WorldCover raster, I used **rioxarray** instead of **rasterio**. But before working on the labels, we can also quickly check that the Xarray generated by opening on e of the seasonal raster with **rioxarray** contains the updated information:

# %%
rxr.open_rasterio(SEASONAL_SCENES[0])

# %%
labels = rxr.open_rasterio(WORLDCOVER_LABELS)

# %%
labels

# %% [markdown]
# Wait, we see that there is a lot of info already there! In particular, we can see that:
#
# - The `product_tile` is wrong because we know from running the script for the WorldCover download that we used two tiles.
# - The map from class ID to class name is present in the `legend` attributue, but is out of sync:

# %%
np.unique(labels)

# %% [markdown]
# So, let's remap it:

# %%
cfg.worldcover.class_mapping

# %% [markdown]
# The legend is stored as a string version of the dictionary, so we have to parse it:

# %%
labels.attrs["legend"]

# %%
legend = {
    int(k): v
    for k, v in (line.split(maxsplit=1) for line in labels.attrs["legend"].strip().splitlines())
}
legend

# %%
new_legend = {}
for index, name in legend.items():
    new_legend[cfg.worldcover.class_mapping[index]] = name

new_legend

# %%
"\n".join([f"{k} {v}" for k, v in new_legend.items()])

# %%
labels = labels.rio.update_attrs({"legend": "\n".join([f"{k} {v}" for k, v in new_legend.items()])})

# %%
labels.attrs["legend"]

# %%
labels.rio.to_raster(WORLDCOVER_LABELS)

# %%
