[aoi]
name = "andalusia"
# Bounding box expressed in the EPSG:4326.
bounding_box = [
  -6.362565950090263,
  37.00620706676072,
  -5.798434049909736,
  37.45839293323928,
]
tile = "MGRS-30STG"
size = 50_000 # [m]
year = 2022
max_cloud_coverage = 10.0
min_scenes = 30
min_scenes_per_season = 5
single_tile = true

[aoi.candidates]
# longitude/latitude (x, y) points of the candidate regions.
brandeburg = [13.4402, 52.7654]
lombardy = [10.0509, 45.6435]
andalusia = [-6.0805, 37.2323]

[stac]
url = "https://stac.dataspace.copernicus.eu/v1"
collection = "sentinel-2-l2a"
page_size = 20
timeout = 90.0                                  # [s]
max_retries = 6
backoff_factor = 1.5                            # [s] exponential backoff base between retries.
retry_statuses = [429, 500, 502, 503, 504]

[msi]
target_resolution = 10
scl_mask_classes = [0, 1, 3, 7, 8, 9, 10, 11] # classes used to filter rasters.

[msi.bands]
# Bands are identified with the Coperinicus ID.
#
# 10: blue, green, red, NIR.
# 20: red edge 1, red edge 2, red edge 3, narrow NIR, SWIR 1, SWIR 2, SCL.
10 = ["B02_10m", "B03_10m", "B04_10m", "B08_10m"]
20 = [
  "B05_20m",
  "B06_20m",
  "B07_20m",
  "B8A_20m",
  "B11_20m",
  "B12_20m",
  "SCL_20m",
]

[composites]
max_scenes_per_season = 10 # we could need it to limit computational resources.
tiles_size = 1024          # dimension of the tile window to apply for the composite.

[composites.seasons]
DJF = ["2021-12-01", "2022-02-28"]
MAM = ["2022-03-01", "2022-05-31"]
JJA = ["2022-06-01", "2022-08-31"]
SON = ["2022-09-01", "2022-11-30"]
# indices = ["NDVI", "NDBI", "NDWI"] # Computed per season

[indices.bands_to_channels]
# A map from the band name to the raster channel index for each index.
ndvi = { "nir" = 3, "red" = 2 }
ndbi = { "swir" = 9, "nir" = 3 }
ndwi = { "green" = 1, "nir" = 3 }

[worldcover]
url = "https://esa-worldcover.s3.eu-central-1.amazonaws.com"
grid_url = "https://esa-worldcover.s3.eu-central-1.amazonaws.com/esa_worldcover_grid.geojson"
version = "v200"
year = 2021

[worldcover.class_to_color]
0 = [255, 255, 255]
1 = [0, 100, 0]
2 = [255, 187, 34]
3 = [255, 255, 76]
4 = [240, 150, 255]
5 = [250, 0, 0]
6 = [180, 180, 180]
7 = [240, 240, 240]
8 = [0, 100, 200]
9 = [0, 150, 160]
10 = [0, 207, 117]
11 = [250, 230, 160]

[worldcover.class_mapping]
0 = 0
10 = 1
20 = 2
30 = 3
40 = 4
50 = 5
60 = 6
70 = 7
80 = 8
90 = 9
95 = 10
100 = 11

[worldcover.class_names]
0 = "No Data"
1 = "Tree Cover"
2 = "Shrubland"
3 = "Grassland"
4 = "Cropland"
5 = "Built-up"
6 = "Bare/Sparse vegetation"
7 = "Snow and ice"
8 = "Permanent water bodies"
9 = "Herbaceous wetland"
10 = "Mangroves"
11 = "Moss and lichen"

[patches]
seed = 3
size = 256        # [pixel]
block_size = 1024
buffer = 1000     # [m]

[patches.split]
train = 0.7
test = 0.15
val = 0.15
