[colors]
text      = "white"
facecolor = "black"

[colors.prop_cycle]
0 = '#1B4965' # ocean blue
1 = '#2A9D8F' # teal green
2 = '#E9C46A' # sand
3 = '#F4A261' # clay orange
4 = '#E76F51' # terracotta
5 = '#6A4C93' # plum violet
6 = '#5C80BC' # slate blue
7 = '#606C38' # olive

[font.size]
title    = 18
subtitle = 16
legend   = 9
labels   = 13
